server:
    port: 18084

spring:
    application:
        name: notification-service
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            value-serializer: org.apache.kafka.common.serialization.StringDeserializer
            key-serializer: org.apache.kafka.common.serialization.StringDeserializer
            group-id: ${spring.application.name}
            auto-offset-reset: latest
            enable-auto-commit: false
            properties:
                isolation.level: read_committed			
    mail:
        host: smtp.163.com
        port: 465
        username: bamboo_pengkezhu@163.com
        password: xxxxxx 
        protocol: smtp
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    ssl:
                        enable: true								
app:
    kafka:
        notification:
            topic: notification-email-triggered-topic

logging:
    level:
        me.bamboo: debug
    pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"