server:
    port: 18082

spring:
    application:
        name: book-service
    datasource:
        url: jdbc:postgresql://localhost:15432/bookdb
        username: booksys
        password: booksys
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
    kafka:
        bootstrap-servers: localhost:9092
        producer:
#            transaction-id-prefix: tx-${spring.application.name}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
    kafka:
        book:
            topic: book-created-topic

logging:
    level:
        me.bamboo: debug
    pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"