server:
    port: 18081

spring:
    application:
        name: account-service
    datasource:
        url: jdbc:postgresql://localhost:15432/accountdb
        username: booksys
        password: booksys
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
    kafka:
        bootstrap-servers: localhost:9092
        producer:
#            transaction-id-prefix: tx-${spring.application.name}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
    kafka:
        account:
            topic: account-created-topic
        search-preference:
            topic: search-preference-created-topic